# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Test

on:
  workflow_dispatch:

jobs:
  
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: build-win,   os: windows-latest, shell: 'msys2 {0}'}
    
    steps:
        
    - name: 'Setup MSYS2'
      if: ${{ contains( matrix.platform.name, 'win') }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
        pacboy: >-
          make:x
          toolchain:x
          cmake:x
          ninja:x
          openal:x
        
    - name: Test build system
      run: which make
